#!/usr/bin/env python


from rawr import main


if __name__ == '__main__':
    
    from optparse import OptionParser
    
    usage = """rawr -s server -p password -t title -m message"""

    parser = OptionParser(usage)
    parser.add_option("-t", "--title", dest="title", 
            help="Growl notification title.")
    parser.add_option("-m", "--message", dest="message",
            help="Growl notification message.")

    parser.add_option("-s", "--server", dest="server",
            help="Growl host server name or IP.")
    parser.add_option("-p", "--password", dest="password",
            help="Growl server password.")

    parser.add_option("-a", "--application", dest="application",
            help="Growl application name.", default="rawr",)
    parser.add_option("-n", "--notification", dest="notification",
            help="Growl application notification name.", default="default",)

    parser.add_option("-r", "--register", dest="register", default=True,
            help="Should rawr attempt to register the application?",)

    (options, args) = parser.parse_args()

    main(options)
